function alpha = param2alpha(params)
%% To convert the results generated by Analysis_Single/Ensemble into alpha values
size_p = length(params);
alpha = zeros(1,size_p);
for search = 1:size_p
    alpha(search) = params{search}(1);
end
